# Generated by Django 3.1.1 on 2022-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('centribot_user_id', models.CharField(default=None, max_length=255)),
                ('mobile_id', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=None)),
                ('updated_at', models.BigIntegerField(default=None, null=True)),
            ],
        ),
    ]
