# Generated by Django 3.1.1 on 2022-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstoken',
            name='mobile_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
