apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "centridesk-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "centridesk-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "centridesk-backend.fullname" . }}-config
    deletionPolicy: Retain
  data:
  - secretKey: config.json
    remoteRef:
      key: {{ .Release.Namespace }}/{{ include "centridesk-backend.fullname" . }}
      property: config.json
