apiVersion: v1
kind: Service
metadata:
  name: {{ include "centridesk-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}    
  labels:
    {{- include "centridesk-backend.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "centridesk-backend.selectorLabels" . | nindent 4 }}
