# Generated by Django 3.1.1 on 2022-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_centribot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPlatformProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255, unique=True)),
                ('centridesk', models.BooleanField(default=None, null=True)),
                ('centripush', models.BooleanField(default=None, null=True)),
            ],
            options={
                'db_table': 'api_accountsplatformproducts',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('dialog_flow_id', models.CharField(default=None, max_length=200)),
                ('lang', models.CharField(default=None, max_length=200)),
                ('account_id', models.CharField(default=None, max_length=200, null=True)),
                ('timezone', models.CharField(default=None, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sandbox', models.BooleanField(default=False)),
                ('sandbox_id', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=None)),
                ('updated_at', models.BigIntegerField(null=True)),
                ('deactivated_at', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'api_projects',
            },
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'api_webhooks',
            },
        ),
        migrations.CreateModel(
            name='WhatsappTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('project_id', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('parameters_count', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=None)),
                ('requested_at', models.BigIntegerField(default=None, null=True)),
                ('approved_at', models.BigIntegerField(default=None, null=True)),
                ('rejected_at', models.BigIntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'api_whatsapptemplates',
            },
        ),
    ]
