# Generated by Django 3.1.1 on 2024-03-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_centribot', '0002_accountsplatformproducts_projects_webhooks_whatsapptemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplates',
            name='buttons',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplates',
            name='footer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplates',
            name='header',
            field=models.TextField(null=True),
        ),
    ]
